apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
  namespace: ledger
type: Opaque
stringData: # change this to 'data:' to use base64 encoded strings instead of plaintext
  root_password: admin
  ledger_user: ledger
  ledger_pass: password